//{{NO_DEPENDENCIES}}

#define IDS_APP_TITLE			101

#define IDD_HELLOWORLD_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_HELLOWORLD			107
#define IDI_HELLOWORLD_SMALL	108
#define IDC_HELLOWORLD			109
#define IDR_MAINFRAME			128
#define IDC_MYICON				2
#ifndef IDC_STATIC
#   define IDC_STATIC				-1
#endif


#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
